In [56]:
import pandas as pd
import json

In [57]:
data = pd.read_csv('../dataset/data_train_eli - Sheet1 (1).csv')
data

,G001,G002,G003,G004,G005,G006,G007,G008,G009,G010,Kode Kerusakan
0,ya,tidak,tidak,tidak,tidak,tidak,tidak,tidak,tidak,ya,K001
1,ya,tidak,tidak,tidak,tidak,tidak,tidak,tidak,tidak,tidak,K001
2,ya,tidak,tidak,tidak,tidak,tidak,tidak,tidak,tidak,tidak,K001
3,ya,tidak,tidak,tidak,tidak,tidak,tidak,tidak,tidak,tidak,K002
4,ya,tidak,tidak,tidak,tidak,tidak,tidak,tidak,tidak,tidak,K003
...,...,...,...,...,...,...,...,...,...,...,...
67,ya,tidak,ya,tidak,tidak,tidak,tidak,tidak,tidak,ya,K031
68,ya,tidak,ya,tidak,tidak,tidak,tidak,tidak,tidak,tidak,K031
69,tidak,ya,tidak,tidak,ya,tidak,tidak,tidak,tidak,ya,K032
70,tidak,tidak,tidak,tidak,ya,tidak,tidak,tidak,tidak,ya,K032
71,tidak,tidak,tidak,tidak,ya,tidak,tidak,tidak,tidak,ya,K032

In [58]:
# data['Kode Kerusakan']

# total = data['Kode Kerusakan'].count()
# per_data = data['Kode Kerusakan'].value_counts()

# data_ = {'K011': 5,
#  'K025': 4,
#  'K024': 4,
#  'K001': 3,
#  'K028': 3,
#  'K022': 3,
#  'K014': 3,
#  'K012': 3,
#  'K032': 3,
#  'K007': 3,
#  'K005': 3,
#  'K010': 2,
#  'K009': 2,
#  'K031': 2,
#  'K030': 2,
#  'K029': 2,
#  'K004': 2,
#  'K023': 2,
#  'K006': 2,
#  'K021': 2,
#  'K020': 2,
#  'K016': 2,
#  'K015': 2,
#  'K008': 2,
#  'K017': 2,
#  'K019': 1,
#  'K018': 1,
#  'K002': 1,
#  'K026': 1,
#  'K027': 1,
#  'K003': 1,
#  'K013': 1}

# data_div = []
# for k,v in data_.items():
#     data_div.append({
#         "name":k,
#         "count":v / total
#     })

# data_div